@extends('layouts.app')
@section('title', 'Home - Tirta Nirwana')

@section('content')
    @livewire('hero-section')
    @livewire('aboutsection')
    @livewire('stats-section')
    @livewire('services-section')
    @livewire('clients-section')
    @livewire('testimonials-section')
    @livewire('team-section')
    @livewire('gallery-section')
    @livewire('contact-section')
    @livewire('faq-section')
    @livewire('blog-section')
@endsection